### ISSUE TITLE
there is an extra ")" in renv.lock file

### ISSUE THREAD

**Issue by y1lan** [icmccorm/ffickle#1]
When I tried to build the project,  I encountered an error:
```
Error in (function (err)  : Failed to parse 'renv.lock':
4:5: unexpected string constant
3:     "Version"= "4.3.1",)
4:     "Repositories"

```
which is obvious  for the extra ")" in line 3, i.e. https://github.com/icmccorm/mirilli/blob/ade82d213b14aca662930cfc6c9f1c2a89a394d2/renv.lock#L3.

**Comment by icmccorm** [comment]
Whups! Should be fixed in e370456
