### ISSUE TITLE
There is no command to initialize the rllvm-as submodule.

### ISSUE THREAD

**Issue by y1lan** [icmccorm/ffickle#2]
In the Dockerfile, on line 47 https://github.com/icmccorm/mirilli/blob/e3704567c3763e5178a45c9ce777f5a290e708e1/Dockerfile#L47, before initializing the inkwell and llvm-sys submodules, there is no command for initializing the rllvm-as submodule, which results in errors like the following when attempting to execute the commands:
```
error: pathspec './inkwell' did not match any file(s) known to git
```

**Comment by icmccorm** [comment]
This should be fixed now in 6ea88f5.
